dist: trusty
sudo: true
language: cpp

addons:
  apt:
    update: true
    packages:
        - ncurses-dev

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      compiler: clang

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo apt-get install libgtest-dev
    - CPPURSES_SOURCE_DIR=$(pwd)
    - cd /usr/src/gtest
    - sudo env "PATH=$PATH" cmake CMakeLists.txt
    - sudo make
    - sudo cp *.a /usr/lib
    - cd ${CPPURSES_SOURCE_DIR}

script:
    - mkdir build && cd build
    - cmake ..
    - cmake --build . --target demos
    - cmake --build . --target tests
    - ctest

notifications:
    email: false
